model:
  img_size:
  - 128
  - 1024
  patch_size: 16
  stride: 16
  in_chans: 1
  embed_dim: 768
  depth: 12
  num_heads: 12
  decoder_embed_dim: 512
  decoder_depth: 2
  decoder_num_heads: 16
  mlp_ratio: 4.0
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  sr: 44100