# pytorch_lightning==2.1.0
seed_everything: 123
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: 100000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 4
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  optimizer: 
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0001
      eps: 1e-8
      weight_decay: 0
  img_size:
  - 128
  - 1024
  patch_size: 16
  stride: 16
  in_chans: 1
  embed_dim: 768
  depth: 12
  num_heads: 12
  decoder_embed_dim: 512
  decoder_depth: 2
  decoder_num_heads: 16
  mlp_ratio: 4.0
  norm_pix_loss: false
  audio_exp: true
  alpha: 0.0
  temperature: 0.2
  mode: 0
  contextual_depth: 8
  use_custom_patch: false
  split_pos: false
  pos_trainable: false
  use_nce: false
  beta: 4.0
  decoder_mode: 0
  mask_t_prob: 0.6
  mask_f_prob: 0.5
  mask_2d: false
  epoch: 0
  no_shift: false
  mask_ratio: 0.8
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  sr: 44100
data:
  audio_dir: null
  target_len_s: null
  target_sr: 44100
  target_n_samples: 524287
  augmentations: null
  batch_size: 32
  num_workers: 8
  transform: false
  val_split: 0.05
log: false
log_model: false
ckpt_path: checkpoints
resume_id: null
resume_from_checkpoint: null